version: "3"

services:

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_DATABASE=test
    volumes:
      - /data/db:/data/db
    networks:
      - spring-mysql
    ports:
      - 27017:27017

  backend:
    image: dc-task
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - DATABASE_HOST=mongodb
      - DATABASE_NAME=test
    depends_on:
      - mongodb
    networks:
      - spring-mysql
    ports:
      - 8080:8080

networks:
  spring-mysql:
